version: '3.8'
services:
  dev_db:
    image: postgres:13
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    networks:
      - nest_bookmarkAPI
networks:
  nest_bookmarkAPI:
